export const state = {
  userId: '',
  courses: [],
  pollingTimer: null,
  autoPollingTimer: null,
  currentPage: 'dashboard',
  lastPlayerStatus: '',
  autoScheduleHours: [9, 13, 18, 23],
  autoEnabled: false,
  currentTerm: '',
  selectedTerm: null,   // null = 현재 학기
  selectedLogType: '',
  currentCourseId: '',
  currentCourseName: '',
  currentSummaryId: '',
  downloadTaskTimers: {},
  activeDownloads: {},   // lecture_url -> taskId (검색/필터 재렌더링에도 진행 중 다운로드 폴링을 다시 붙이기 위함)
  settings: {
    DOWNLOAD_ENABLED: 'false',
    DOWNLOAD_RULE: 'mp4',
    AUTO_DOWNLOAD_AFTER_PLAY: 'false',
    STT_ENABLED: 'false',
    STT_DELETE_AUDIO_AFTER_TRANSCRIBE: 'false',
    AI_ENABLED: 'false',
    AI_AGENT: 'gemini',
    GEMINI_MODEL: '',
    SUMMARY_PROMPT_TEMPLATE: '',
    SUMMARY_PROMPT_DEFAULT: '',
    SUMMARY_PROMPT_EXTRA: '',
    SUMMARY_DELETE_TEXT_AFTER_SUMMARIZE: 'false',
  },
  settingsLoaded: false,
  autoDownloadStartedFor: '',
  deadlineChecked: false,
  currentCourseDetail: null,
};
